# Copyright 2020-2024 The MathWorks, Inc.

# Workflow that contains jobs to test MATLAB Proxy
name: Testing MATLAB Proxy Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  # Runs unit tests
  call-run-unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml

  # Runs integration tests
  call-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
    secrets: inherit
